// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace database.CompiledModels
{
    [DbContext(typeof(RecipeContext))]
    public partial class BakedRecipeContextModel : RuntimeModel
    {
        static BakedRecipeContextModel()
        {
            var model = new BakedRecipeContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static BakedRecipeContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
