// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace database.CompiledModels
{
    public partial class BakedRecipeContextModel
    {
        partial void Initialize()
        {
            var bakedRecipe = BakedRecipeEntityType.Create(this);
            var ingredient = IngredientEntityType.Create(this);

            IngredientEntityType.CreateForeignKey1(ingredient, bakedRecipe);

            BakedRecipeEntityType.CreateAnnotations(bakedRecipe);
            IngredientEntityType.CreateAnnotations(ingredient);

            AddAnnotation("ProductVersion", "7.0.10");
        }
    }
}
