name: .NET

on:
  push:
    branches: ["main"]
    paths-ignore: 
      - 'client-app/**'
  pull_request:
    branches: ["main"]
    paths-ignore: 
      - 'client-app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            core/domain/packages.lock.json
            database/packages.lock.json
            tests_api/packages.lock.json
            tests_api_xunit/packages.lock.json
            tests_core/packages.lock.json
            webapi/packages.lock.json
      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
